### PR TITLE
Add templates (community standards)

### LINKED ISSUE #6: Community guidelines: add a bug report template

### LINKED ISSUE #7: Community guidelines: add a feature request template

### LINKED ISSUE #10: Community guidelines: add a pull request template
Description should potentially include stuff like

- [ ] I read the CONTRIBUTION guidelines
- [ ] I made sure documentation is up-to-date regarding my changes
- [ ] I self-reviewed my changes

### PR DESCRIPTION
**Pull request by paulo-ferraz-oliveira**
We don't have a contributing guide yet (the pull request template points to a file that doesn't exist), but I intend on writing a small one.

If you prefer I can add the file already with text "Nothing to see here", for the time being.

Closes #6.
Closes #7
Closes #10.

### CODE REVIEW

**Comment by wojtekmach** [comment]
I think a CONTRIBUTING.md will be nice, it would mention the command to test things locally. I don't think these templates are useful though, I'd add them down the road based on the issues/PRs people send.

**Comment by paulo-ferraz-oliveira** [comment]
The usefulness for these templates, for me, is:

1. guidance for contributors (even if there's not a lot of content in the templates)
2. the labels
3. the version-related information we request

What do you think are the disadvantages of having them, otoh?

**Comment by wojtekmach** [comment]
In my opinion these templates are adding little guidance and so little to no value to this particular project anytime soon. They are stating pretty obvious things and asking for information that any reasonable enough issue would provide anyway. As an aside, asking in the PR template the committer to self-review their changes feels a little bit belittling to be honest, they submitted a PR, we can assume they did in fact review their stuff before submitting. When we say an issue is either a bug or feature request, what if it's neither? Say, someone just wants to ask a question about the project. I have seen large projects add process (templates, guidelines, etc) to help triaging the sheer amount of incoming issues/PRs. Answering questions in issues in large projects is rather undesirable but in small projects I believe it's totally fine. Receiving large amount of low quality issues (missing basic information, for example) would be a huge drag for sure. I'm not against adding stuff like this down the road especially if we get low quality input and/or we can make it easier for folks to contribute. But I wouldn't start with it, let's first get, you know, some issues and contributions.

That being said, if you or anyone else feel strongly about adding these right now, it's not a deal breaker for me.

**Comment by paulo-ferraz-oliveira** [comment]
"I have performed a self-review of my changes" is probably not well explained; and this is potentially due to the fact I've used it in many companies before I might've gotten used to its hidden semantics, rather than the words; in any case, it was never brought up as belittling 🤷, but I get your point, I think. To further it: it's about going over the changes in the PR and making not so obvious decisions (that you can't explain in context with a commit message), explained in the "Files changed" view - in GitHub's case.

I'll close the pull requests, as I don't seem to feel as strong about having them as you about not having them. In time, hopefully not even required, we'll create them.

**Pull request closed without merging**
